#!/bin/bash

if [ -z "$1" ]; then
  echo "ERROR: No se ha proporcionado un directorio para descargar el repo."
  exit 1
fi

ruta="archive/refs/heads/main.zip"

repo=$1/$ruta

echo "Bajando el repo: $repo"

wget $repo

echo "Descarga lista"
unzip main.zip

rm main.zip

echo "Descompresion lista"

find . -type d -name "*-main" -exec bash -c 'for dirpath; do mv "$dirpath" "${dirpath%-main}"; done' bash {} +
