#!/bin/bash

ruta="archive/refs/heads/main.zip"

repo=$1/$ruta

echo "Bajando el repo: $repo"

wget $repo

echo "Descarga lista"
unzip main.zip

rm main.zip

echo "Descompresion lista"

find . -type d -name "*-main" -exec bash -c 'for dirpath; do mv "$dirpath" "${dirpath%-main}"; done' bash {} +